# Generated by Django 4.1.4 on 2022-12-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kategori Adı')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Video Başlığı')),
                ('image', models.FileField(upload_to='', verbose_name='Video Resmi')),
                ('date_now', models.DateTimeField(auto_now_add=True, verbose_name='Yayın Tarihi')),
                ('imdb', models.FloatField(verbose_name='IMDB')),
                ('category', models.ManyToManyField(to='appMy.category', verbose_name='Kategori')),
            ],
        ),
        migrations.AddField(
            model_name='profil',
            name='favori',
            field=models.ManyToManyField(to='appMy.video', verbose_name='Favori Videolar'),
        ),
    ]
